apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ui-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /guestbook
          backend:
            serviceName: kustomize-guestbook-ui
            servicePort: 80
